
server:
  port: 8080

eureka:
  client:
    service-url:
      #用来指定注册服务中心地址
      defaultZone: http://localhost:1111/eureka/
  instance:
    instance-id: apiGatewayService
    prefer-ip-address: true

spring:
  application:
    name: api-gateway

zuul:
  routes:
    product-service: /apiGateway/product/**
    order-service: /apiGateway/order/**
    ignored-patterns: /*-service/**
    ignored-services: product-service

ribbon:
    ConnectTimeout: 6000  #连接
    ReadTimeout: 6000 #读取超时时间

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 6000
